# Generated by Django 6.0.6 on 2026-06-08 09:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='The title of the argument map.', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Detailed description or goal of the map.')),
                ('is_public', models.BooleanField(default=True, help_text='Whether this map is publicly visible or private.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(help_text='The owner/creator of the map.', on_delete=django.db.models.deletion.CASCADE, related_name='created_maps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text="Short summary of the node's statement.", max_length=255)),
                ('text', models.TextField(blank=True, default='', help_text='Detailed elaboration, links, or context.')),
                ('node_type', models.CharField(choices=[('claim', 'Claim'), ('argument', 'Argument'), ('evidence', 'Evidence'), ('question', 'Question')], default='claim', help_text='The logical role of this node.', max_length=20)),
                ('x_position', models.FloatField(default=0.0, help_text='Visual X position on canvas.')),
                ('y_position', models.FloatField(default=0.0, help_text='Visual Y position on canvas.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(help_text='The user who created this node.', on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to=settings.AUTH_USER_MODEL)),
                ('map', models.ForeignKey(help_text='The map this node belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='maps.map')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('edge_type', models.CharField(choices=[('support', 'Support'), ('counter', 'Counter')], default='support', help_text='Whether this edge supports or counters the target node.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(help_text='The user who created this edge.', on_delete=django.db.models.deletion.CASCADE, related_name='edges', to=settings.AUTH_USER_MODEL)),
                ('map', models.ForeignKey(help_text='The map this edge belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='maps.map')),
                ('source', models.ForeignKey(help_text='The supporting or countering node.', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='maps.node')),
                ('target', models.ForeignKey(help_text='The node being supported or countered.', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='maps.node')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='map',
            index=models.Index(fields=['creator'], name='maps_map_creator_73147b_idx'),
        ),
        migrations.AddIndex(
            model_name='map',
            index=models.Index(fields=['-created_at'], name='maps_map_created_5575a9_idx'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['map', 'created_at'], name='maps_node_map_id_6c435e_idx'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['creator'], name='maps_node_creator_d7dbfd_idx'),
        ),
        migrations.AddIndex(
            model_name='edge',
            index=models.Index(fields=['map'], name='maps_edge_map_id_ee06c5_idx'),
        ),
        migrations.AddConstraint(
            model_name='edge',
            constraint=models.CheckConstraint(condition=models.Q(('source', models.F('target')), _negated=True), name='prevent_self_loop'),
        ),
        migrations.AddConstraint(
            model_name='edge',
            constraint=models.UniqueConstraint(fields=('source', 'target'), name='unique_source_target_edge'),
        ),
    ]
