# Generated by Django 6.0.6 on 2026-06-08 10:32
# Manually restructured: safe data migration that preserves title+text into content.

# pyrefly: ignore [missing-import]
from django.db import migrations, models


def merge_title_text_into_content(apps, schema_editor):
    """
    Data migration: concatenate existing title and text into the new content field.
    Format: "title\n\ntext" if text exists, otherwise just "title".
    """
    Node = apps.get_model('maps', 'Node')
    for node in Node.objects.all():
        parts = [node.title]
        if node.text:
            parts.append(node.text)
        node.content = '\n\n'.join(parts)
        node.save(update_fields=['content'])


def split_content_back(apps, schema_editor):
    """
    Reverse data migration: take first line as title, rest as text.
    """
    Node = apps.get_model('maps', 'Node')
    for node in Node.objects.all():
        lines = node.content.split('\n\n', 1)
        node.title = lines[0][:255]  # CharField max_length was 255
        node.text = lines[1] if len(lines) > 1 else ''
        node.save(update_fields=['title', 'text'])


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        # Step 1: Add the new content field (nullable temporarily)
        migrations.AddField(
            model_name='node',
            name='content',
            field=models.TextField(
                default='',
                help_text='The argument, claim, evidence, or question this node represents.',
            ),
            preserve_default=False,
        ),

        # Step 2: Copy title + text → content
        migrations.RunPython(
            merge_title_text_into_content,
            split_content_back,
        ),

        # Step 3: Remove the old fields
        migrations.RemoveField(
            model_name='node',
            name='title',
        ),
        migrations.RemoveField(
            model_name='node',
            name='text',
        ),
    ]
