# Generated by Django 6.0.6 on 2026-06-08 18:20

# pyrefly: ignore [missing-import]
import django.db.models.deletion
import uuid
# pyrefly: ignore [missing-import]
from django.conf import settings
# pyrefly: ignore [missing-import]
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_remove_node_text_remove_node_title_node_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attachment_type', models.CharField(choices=[('image', 'Image'), ('gif', 'GIF'), ('video', 'Video'), ('link', 'Link')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='attachments/%Y/%m/')),
                ('external_url', models.URLField(blank=True, default='', max_length=500)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='maps.node')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['node', 'created_at'], name='maps_nodeat_node_id_284f0a_idx')],
            },
        ),
        migrations.CreateModel(
            name='NodeVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vote_type', models.CharField(choices=[('upvote', 'Upvote'), ('downvote', 'Downvote')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='maps.node')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['node'], name='maps_nodevo_node_id_8b28f6_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'node'), name='unique_user_node_vote')],
            },
        ),
    ]
