# Generated by Django 6.0.6 on 2026-06-08 18:39

import uuid
from django.conf import settings
from django.db import migrations, models


def create_root_nodes_for_existing_maps(apps, schema_editor):
    Map = apps.get_model('maps', 'Map')
    Node = apps.get_model('maps', 'Node')

    for map_obj in Map.objects.all():
        if Node.objects.filter(map=map_obj, is_root=True).exists():
            continue
        Node.objects.create(
            id=uuid.uuid4(),
            map=map_obj,
            creator=map_obj.creator,
            content=map_obj.title,
            node_type='claim',
            is_root=True,
            x_position=0.0,
            y_position=0.0,
        )


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('maps', '0003_nodeattachment_nodevote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='is_root',
            field=models.BooleanField(default=False, help_text='System root node — one per map, mirrors map title.'),
        ),
        migrations.RunPython(
            create_root_nodes_for_existing_maps,
            migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['map', 'is_root'], name='maps_node_map_id_603231_idx'),
        ),
        migrations.AddConstraint(
            model_name='node',
            constraint=models.UniqueConstraint(condition=models.Q(('is_root', True)), fields=('map',), name='unique_root_node_per_map'),
        ),
    ]
