# Generated by Django 6.0.6 on 2026-06-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_add_root_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='board_type',
            field=models.CharField(choices=[('freeform', 'Freeform'), ('debate', 'Debate')], default='freeform', help_text='Board type chosen at creation. Immutable after creation.', max_length=20),
        ),
        migrations.AlterField(
            model_name='edge',
            name='edge_type',
            field=models.CharField(choices=[('support', 'Support'), ('counter', 'Counter'), ('reference', 'Reference')], default='support', help_text='Whether this edge supports or counters the target node.', max_length=20),
        ),
    ]
