# Generated by Django 6.0.6 on 2026-06-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_map_board_type_alter_edge_edge_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeattachment',
            name='imagekit_file_id',
            field=models.CharField(blank=True, default='', help_text='ImageKit fileId — used to delete the CDN file when the attachment is removed.', max_length=255),
        ),
        migrations.AddField(
            model_name='nodeattachment',
            name='imagekit_thumbnail_url',
            field=models.URLField(blank=True, default='', help_text='ImageKit thumbnail URL (400×300, images/GIFs only).', max_length=500),
        ),
        migrations.AlterField(
            model_name='nodeattachment',
            name='external_url',
            field=models.URLField(blank=True, default='', help_text='CDN URL (ImageKit) for media, YouTube URL for video links, or link URL.', max_length=500),
        ),
        migrations.AlterField(
            model_name='nodeattachment',
            name='file',
            field=models.FileField(blank=True, help_text='Legacy local file storage. New uploads use ImageKit (external_url).', null=True, upload_to='attachments/%Y/%m/'),
        ),
    ]
